"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

fib_0 = 0;
fib_1 = 1;

next_fib = 0;
sum_of_even_fibs = 0;
under_value = 4000000
while (next_fib < under_value):
	next_fib = fib_0 + fib_1
	fib_0 = fib_1
	fib_1 = next_fib
	if next_fib <= under_value and next_fib % 2 == 0:
		sum_of_even_fibs += next_fib

print sum_of_even_fibs

